"""added type field

Revision ID: 85f76c04d10a
Revises: 4a415c8b05e4
Create Date: 2023-11-27 20:17:28.874064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f76c04d10a'
down_revision = '4a415c8b05e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('news', 'publication', 'other', name='enumposttype'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
